[
    {
        "id": "app.error.reportErrorTitle",
        "description": "title for report error modal",
        "defaultMessage": "Segnala un errore"
    },
    {
        "id": "app.error.thankYouForYourFeedback",
        "description": "thank you for feedback",
        "defaultMessage": "Grazie per il tuo feedback!"
    },
    {
        "id": "app.error.copyTheFollowingLines",
        "description": "text explaining what to do to report an issue on GH",
        "defaultMessage": "Per favore copia le righe seguenti e crea una nuova segnalazione su {githubLink}."
    },
    {
        "id": "app.error.alsoCheckForOpenedIssues",
        "description": "text suggesting to check for existing issues",
        "defaultMessage": "Verifica anche che non ci siano segnalazione già aperte per questo errore!"
    },
    {
        "id": "app.error.backupKeys",
        "description": "error message for backup keys action",
        "defaultMessage": "La generazione del backup non è riuscita. Riprova"
    },
    {
        "id": "app.error.commentsDownvote",
        "description": "error message for downvoting a comment",
        "defaultMessage": "Si è verificato un errore durante il downvoting di un commento"
    },
    {
        "id": "app.error.commentsPublish",
        "description": "error message for publishing a comment",
        "defaultMessage": "Si è verificato un errore durante la pubblicazione di un commento"
    },
    {
        "id": "app.error.commentsUpvote",
        "description": "error message for upvoting a comment",
        "defaultMessage": "Si è verificato un errore durante l'upvoting di un commento"
    },
    {
        "id": "app.error.dashboardAdd",
        "description": "error message for creating a new board",
        "defaultMessage": "Si è verificato un errore durante il salvataggio della nuova board"
    },
    {
        "id": "app.error.dashboardAddColumn",
        "description": "error message for adding a column to a board",
        "defaultMessage": "Si è verificato un errore durante il salvataggio della nuova colonna"
    },
    {
        "id": "app.error.dashboardDelete",
        "description": "error message for deleting a board",
        "defaultMessage": "Si è verificato un errore durante la cancellazione della tua board"
    },
    {
        "id": "app.error.dashboardDeleteColumn",
        "description": "error message for removing a column from a board",
        "defaultMessage": "Si è verificato un errore durante la cancellazione della tua colonna"
    },
    {
        "id": "app.error.dashboardGetActive",
        "description": "error message for fetching the active board",
        "defaultMessage": "Si è verificato un errore durante la richiesta della board attiva"
    },
    {
        "id": "app.error.dashboardGetAll",
        "description": "error message for fetching all boards",
        "defaultMessage": "Si è verificato un errore durante la richiesta della tua board"
    },
    {
        "id": "app.error.dashboardSetActive",
        "description": "error message for setting the active board",
        "defaultMessage": "Si è verificato un errore durante il salvataggio della board attiva"
    },
    {
        "id": "app.error.dashboardUpdateColumn",
        "description": "error message for updating a column",
        "defaultMessage": "Si è verificato un errore durante l'aggiornamente della tua colonna"
    },
    {
        "id": "app.error.draftAutosave",
        "description": "error message for autosaving a draft",
        "defaultMessage": "Impossibile salvare le modifiche più recenti di questa bozza"
    },
    {
        "id": "app.error.draftPublish",
        "description": "error message for publishing a draft",
        "defaultMessage": "Si è verificato un errore durante la pubblicazione della tua bozza"
    },
    {
        "id": "app.error.entriesGetAsDrafts",
        "description": "error message for fetching your own entries",
        "defaultMessage": "Si è verificato un errore durante il tentativo di recuperare le tue voci. Sto mostrando solo bozze locali"
    },
    {
        "id": "app.error.entryClaim",
        "description": "error message for collecting Essence for an entry",
        "defaultMessage": "Si è verificato un errore durante la raccolta di Essenza per {entryTitle}"
    },
    {
        "id": "app.error.entryClaimVote",
        "description": "error message for collecting Essence for a vote",
        "defaultMessage": "Si è verificato un errore durante la raccolta di Essenza per {entryTitle}"
    },
    {
        "id": "app.error.entryDownvote",
        "description": "error message for downvoting an entry",
        "defaultMessage": "Si è verificato un errore durante il downvoting di {entryTitle}"
    },
    {
        "id": "app.error.entryGetFull",
        "description": "error message for fetching a full entry",
        "defaultMessage": "Si è verificato un errore durante la richiesta dei dati in ingresso"
    },
    {
        "id": "app.error.entryListIterator",
        "description": "error message for fetching entries in a list",
        "defaultMessage": "Si è verificato un errore durante la richiesta delle voci in una lista"
    },
    {
        "id": "app.error.entryUpvote",
        "description": "error message for upvoting an entry",
        "defaultMessage": "Si è verificato un errore durante l'upvoting di {entryTitle}"
    },
    {
        "id": "app.error.errorNotificationTitle",
        "description": "title for error notifcations",
        "defaultMessage": "Codice errore {errorCode}"
    },
    {
        "id": "app.error.fatalError",
        "description": "title for fatal error modal",
        "defaultMessage": "Errore irreversibile"
    },
    {
        "id": "app.error.generalSettings",
        "description": "error message for fetching general settings",
        "defaultMessage": "Si è verificato un errore durante il recupero delle tue impostazioni generali"
    },
    {
        "id": "app.error.gethGetOptions",
        "description": "error message for fetching geth options",
        "defaultMessage": "Si è verificato un errore durante il recupero delle opzioni del servizio geth"
    },
    {
        "id": "app.error.gethGetStatus",
        "description": "error message for fetching geth status",
        "defaultMessage": "Si è verificato un errore durante il recupero dello stato del servizio geth"
    },
    {
        "id": "app.error.gethGetSyncStatus",
        "description": "error message for fetching geth synchronization status",
        "defaultMessage": "Si è verificato un errore durante il recupero dello stato della sincronizzazione"
    },
    {
        "id": "app.error.gethSaveSettings",
        "description": "error message for saving geth settings",
        "defaultMessage": "Si è verificato un errore durante il salvataggio delle tue impostazioni geth"
    },
    {
        "id": "app.error.gethSettings",
        "description": "error message for fetching geth settings",
        "defaultMessage": "Si è verificato un errore durante il recupero delle tue impostazioni geth"
    },
    {
        "id": "app.error.gethStart",
        "description": "error message for starting geth service",
        "defaultMessage": "Non è stato possibile avviare il servizio geth"
    },
    {
        "id": "app.error.gethStop",
        "description": "error message for stopping geth service",
        "defaultMessage": "Non è stato possibile fermare il servizio geth"
    },
    {
        "id": "app.error.ipfsGetConfig",
        "description": "error message for fetching IPFS service configuration",
        "defaultMessage": "Si è verificato un errore durante il recupero della configurazione del servizio IPFS"
    },
    {
        "id": "app.error.ipfsGetPorts",
        "description": "error message for fetching IPFS ports",
        "defaultMessage": "Si è verificato un errore durante il recupero delle porte del servizio IPFS"
    },
    {
        "id": "app.error.ipfsSaveSettings",
        "description": "error message for saving IPFS settings",
        "defaultMessage": "Si è verificato un errore durante il salvataggio delle tue impostazioni IPFS"
    },
    {
        "id": "app.error.ipfsSetPorts",
        "description": "ipfs set ports error message",
        "defaultMessage": "Si è verificato un errore durante l'impostazione delle porte del servizio Ipfs"
    },
    {
        "id": "app.error.ipfsSettings",
        "description": "error message for fetching IPFS settings",
        "defaultMessage": "Si è verificato un errore durante il recupero delle tue impostazioni IPFS"
    },
    {
        "id": "app.error.ipfsStart",
        "description": "error message for starting IPFS service",
        "defaultMessage": "Non è stato possibile avviare il servizio IPFS"
    },
    {
        "id": "app.error.ipfsGetStatus",
        "description": "error message for fetching IPFS service status",
        "defaultMessage": "Si è verificato un errore durante il recupero dello stato del servizio IPFS"
    },
    {
        "id": "app.error.ipfsStop",
        "description": "error message for stopping IPFS service",
        "defaultMessage": "Non è stato possibile fermare il servizio IPFS"
    },
    {
        "id": "app.error.unexpectedError",
        "description": "a general error (with no error code)",
        "defaultMessage": "Errore imprevisto"
    },
    {
        "id": "app.error.profileBondAeth",
        "description": "error message for bonding (manafying) AETH",
        "defaultMessage": "Si è verificato un errore durante la conversione in Mana di {amount} AETH"
    },
    {
        "id": "app.error.profileCycleAeth",
        "description": "error message for cycling AETH",
        "defaultMessage": "An error occured while cycling {amount} AETH"
    },
    {
        "id": "app.error.profileFreeAeth",
        "description": "error message for freeing AETH that was cycled",
        "defaultMessage": "An error occured while collecting your cycled AETH"
    },
    {
        "id": "app.error.profileGetLocal",
        "description": "error message for fetching local profiles",
        "defaultMessage": "Si è verificato un errore durante la raccolta dei profili locali"
    },
    {
        "id": "app.error.profileGetList",
        "description": "error message for fetching a list of profiles",
        "defaultMessage": "Si è verificato un errore durante la raccolta della lista dei profili"
    },
    {
        "id": "app.error.profileToggleDonations",
        "description": "error message for changing the settings for accepting tips",
        "defaultMessage": "Si è verificato un errore durante il cambiamento delle tue impostazioni tips"
    },
    {
        "id": "app.error.profileTransferAeth",
        "description": "error message for transferring AETH",
        "defaultMessage": "Si è verificato un errore durante il trasferimento di {tokenAmount} AETH"
    },
    {
        "id": "app.error.profileTransferEth",
        "description": "error message for transferring ETH",
        "defaultMessage": "Si è verificato un errore durante il trasferimento di {value} ETH"
    },
    {
        "id": "app.error.profileTransformEssence",
        "description": "error message for transforming Essence in AETH",
        "defaultMessage": "An error occured while transforming {amount} Essence"
    },
    {
        "id": "app.error.profileUpdate",
        "description": "error message for updating your profile",
        "defaultMessage": "Si è verificato un errore durante l'aggiornamente del tuo profilo"
    },
    {
        "id": "app.error.saveGeneralSettings",
        "description": "error message for saving general settings",
        "defaultMessage": "Si è verificato un errore durante il salvataggio del tuo profilo"
    },
    {
        "id": "app.error.appErrorTitle",
        "description": "Title message to display when the app crashes because of an unexpected error",
        "defaultMessage": "Ah snap!"
    },
    {
        "id": "app.error.appErrorSubtitle",
        "description": "Subtitle message to display when the app crashes because of an unexpected error",
        "defaultMessage": "Qualcosa è andato terribilmente storto."
    },
    {
        "id": "app.error.copyError",
        "description": "label for copy to clipboard button",
        "defaultMessage": "Errore di copia sulla clipboard"
    },
    {
        "id": "app.error.profileFaucet",
        "description": "error message for faucet request",
        "defaultMessage": "An error occurred while requesting funds from faucet"
    },
    {
        "id": "app.error.profileRegister",
        "description": "error message for registering your profile",
        "defaultMessage": "An error occured while registering your profile"
    },
    {
        "id": "app.error.profileFollow",
        "description": "error message for profile follow",
        "defaultMessage": "An error occurred while following {ethAddress}"
    },
    {
        "id": "app.error.profileUnfollow",
        "description": "error message for profile unfollow",
        "defaultMessage": "An error occurred while unfollowing {ethAddress}"
    }
]